name: Build CCExtractor on Windows

on:
  push:
    paths:
    - '.github/workflows/build_windows.yml'
    - '**.c'
    - '**.h'
    - 'windows/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
    - '.github/workflows/build_windows.yml'
    - '**.c'
    - '**.h'
    - 'windows/**'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v1
    - name: build Release
      run: "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" ccextractor.sln /p:Configuration=Release
      working-directory: ./windows
    - name: build Debug
      run: "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" ccextractor.sln /p:Configuration=Debug
      working-directory: ./windows
    - name: Prepare artifacts
      run: mkdir ./windows/artifacts
    - name: Copy release artifact
      run: cp ./windows/Release/ccextractorwin.exe ./windows/artifacts/; cp ./windows/Release/ccextractorgui.exe ./windows/artifacts/
    - name: Copy debug artifact
      run: cp ./windows/Debug/ccextractorwin.exe ./windows/artifacts/ccextractorwin_debug.exe; cp ./windows/Debug/ccextractorgui.exe ./windows/artifacts/ccextractorgui_debug.exe
    - uses: actions/upload-artifact@v1
      with:
        name: CCExtractor Windows Release_or_Debug build
        path: ./windows/artifacts
